#ssh_key_keith_path: "SECRET/id_ed25519_keith_HAFXB-W10_WSL2_debian"
#ssh_key_keith_pub_content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFFWfuoIayA2ckiCUfb8h9Q+KiDU1n8Gd5aTVP1kwMKC keith@HAFXB-W10 on WSL2 Debian"

#ssh_key_ansible_path: "SECRET/id_ed25519_ansible"
#ssh_key_ansible_pub_content: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKdHQpgEJ++Sl/NdAiDHjTBFjeSGyndOWGC7hB68HVjW ansible"



ssh_pubkeys:
  keith:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFFWfuoIayA2ckiCUfb8h9Q+KiDU1n8Gd5aTVP1kwMKC keith@HAFXB-W10 on WSL2 Debian
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG0wLwbUCHGcfbpCckCrD9RrIoi+9PuDoKbhen3NlHvK keith@UOITLT-W10 on WSL2 Debian
  ansible:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKdHQpgEJ++Sl/NdAiDHjTBFjeSGyndOWGC7hB68HVjW ansible
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINZf3GLqPOt5J6pa72l6UEFkaI1+sg6U9WRekzrnDKgL ansible@UOITLT-W10 on WSL2 Debian

ssh_key_keith_priv_path: "SECRET/id_ed25519_keith"
ssh_key_ansible_priv_path: "SECRET/id_ed25519_ansible"



admin_users: 
  - keith
  - ansible

cli_users:
  - keith
  - ansible

gui_users:
  - keith

sshd_host_key_paths:
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ecdsa_key.pub
  - /etc/ssh/ssh_host_ed25519_key
  - /etc/ssh/ssh_host_ed25519_key.pub
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_rsa_key.pub

