---
- name: see if {{ item.id }} is installed
  stat:
    path: /home/keith/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{{ item.id }}.xpi
    get_checksum: false
    get_attributes: false
    get_mime: false
  register: firefox_extension_installed
- name: download extension {{ item.id }}
  get_url:
    dest: /home/keith/.mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{{ item.id }}.xpi
    force: true
    mode: 0755
    owner: keith
    group: keith
    url: "{{ item.downloadURL }}"
  when: not firefox_extension_installed.stat.exists

