- name: install firefox (linux)
  hosts: debian
  apt: 
    name: 
      - firefox-esr
      - firefox-esr-l10n-en-ca
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: configure firefox (linux)
  hosts: debian
  become: true
  become_user: keith
  block:
  - name: check firefox profile exists (linux)
    hosts: debian
    stat:
      path: /home/keith/.mozilla/firefox/ansible
    register: firefox_profile_exists_linux
  - name: make new firefox profile (linux)
    hosts: debian
    shell: 
      cmd: |
        /usr/bin/firefox --createprofile "ansible /home/keith/.mozilla/firefox/ansible"
    when: not firefox_profile_exists_linux.stat.exists  

  - name: set default firefox profile (linux)
    hosts: debian
    block:
      - name: remove default profile line (linux)
        lineinfile: 
          path: /home/keith/.mozilla/firefox/profiles.ini
          line: |
            Default=1
          state: absent
      - name: add default profile line (linux)
        blockinfile:
          path: /home/keith/.mozilla/firefox/profiles.ini
          regexp: |
            'Path=ansible'
          block: |
            Path=ansible
            Default=1
          state: present

  - name: install arkenfox user.js and updater (linux)
    hosts: debian
    block:
      - name: get arkenfox user.js (linux)
        get_url:
          dest: /home/keith/.mozilla/firefox/ansible
          force: true
          mode: 0600
          owner: keith
          group: keith
          url: |
            https://raw.githubusercontent.com/arkenfox/user.js/master/user.js
      - name: get arkenfox prefsCleaner (linux)
        get_url:
          dest: /home/keith/.mozilla/firefox/ansible
          force: true
          mode: 0700
          owner: keith
          group: keith
          url: |
            https://raw.githubusercontent.com/arkenfox/user.js/master/prefsCleaner.sh
      - name: get arkenfox updater (linux)
        get_url:
          dest: /home/keith/.mozilla/firefox/ansible
          force: true
          mode: 0700
          owner: keith
          group: keith
          url: |
            https://raw.githubusercontent.com/arkenfox/user.js/master/updater.sh
      - name: copy user-overrides.js (linux)
        template:
          src: user-overrides.js.j2
          dest: /home/keith/.mozilla/firefox/ansible/user-overrides.js
          mode: 0600
          owner: keith
          group: keith



#copy systemd service and timer
#enable systemd timer @keith as ansible user
#if ...last run was awhile ago? then
	#run systemd service @keith as ansible user

#Install and configure floccus


