- name: install firefox (linux)
  tags: firefox
  apt: 
    name: 
      - firefox-esr
      - firefox-esr-l10n-en-ca
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_distribution == 'Debian'

- name: configure firefox (linux)
  tags: firefox
  become: true
  become_user: keith
  when: ansible_distribution == 'Debian'
  block:
  - name: check firefox profile exists (linux)
    stat:
      path: /home/keith/.mozilla/firefox/ansible
    register: firefox_profile_exists_linux
  - name: make new firefox profile (linux)
    shell: 
      cmd: |
        /usr/bin/firefox --createprofile "ansible /home/keith/.mozilla/firefox/ansible"
    when: not firefox_profile_exists_linux.stat.exists

  - name: set default firefox profile (linux)
    block:
      - name: remove default profile line (linux)
        lineinfile: 
          path: /home/keith/.mozilla/firefox/profiles.ini
          line: |
            Default=1
          state: absent
        notify: run_arkenfox_unit
      - name: add default profile line (linux)
        blockinfile:
          path: /home/keith/.mozilla/firefox/profiles.ini
          insertafter: |
            Path=ansible
          block: |
            Default=1
          state: present
        notify: run_arkenfox_unit
  - name: install arkenfox user.js and updater (linux)
    block:
      - name: get arkenfox user.js (linux)
        get_url:
          dest: /home/keith/.mozilla/firefox/ansible
          force: true
          mode: 0600
          owner: keith
          group: keith
          url: |
            https://raw.githubusercontent.com/arkenfox/user.js/master/user.js
        notify: run_arkenfox_unit
      - name: get arkenfox prefsCleaner (linux)
        get_url:
          dest: /home/keith/.mozilla/firefox/ansible
          force: true
          mode: 0700
          owner: keith
          group: keith
          url: |
            https://raw.githubusercontent.com/arkenfox/user.js/master/prefsCleaner.sh
        notify: run_arkenfox_unit
      - name: get arkenfox updater (linux)
        get_url:
          dest: /home/keith/.mozilla/firefox/ansible
          force: true
          mode: 0700
          owner: keith
          group: keith
          url: |
            https://raw.githubusercontent.com/arkenfox/user.js/master/updater.sh
        notify: run_arkenfox_unit
      - name: copy user-overrides.js (linux)
        template:
          src: user-overrides.js.j2
          dest: /home/keith/.mozilla/firefox/ansible/user-overrides.js
          mode: 0600
          owner: keith
          group: keith
        notify: run_arkenfox_unit
      - name: set up arkenfox service
        become: true
        become_user: ansible
        block:
          - name: copy arkenfox service
            template:
              src: arkenfox@.service.j2
              dest: /etc/systemd/system/arkenfox@.service
              mode: 744
              owner: root
              group: root
            notify: run_arkenfox_unit
          - name: copy arkenfox timer
            template:
              src: arkenfox@.timer.j2
              dest: /etc/systemd/system/arkenfox@.timer
              mode: 744
              owner: root
              group: root
            notify: run_arkenfox_unit
          - name: enable arkenfox timer
            systemd:
              name: |
                arkenfox@keith.timer
              state: started
              enabled: yes

#enable systemd timer @keith as ansible user
#if ...last run was awhile ago? then
#run systemd service @keith as ansible user

#Install and configure floccus


