---
#Usage: ansible-playbook run-ansible_linux.yml
- name: run debian common tasks
  hosts: debian
  serial: 
    - 1
    - 10
  become: true
  handlers:
    - import_tasks: handlers.yml
  roles: 
    - debian

- name: run gnome3 tasks
  hosts: gnome3
  serial: 
    - 1
    - 10
  become: true
  handlers:
    - import_tasks: handlers.yml
  roles:
    - gnome3

- name: run firefox tasks
  hosts: firefox
  serial:
    - 1 
    - 10
  become: true
  handlers:
    - import_tasks: handlers.yml
  roles:
    - firefox
