---
- name: test firefox json manipulation
  hosts: firefox
  become: true
  become_user: keith
  tasks:
    - name: load json stub to be added
      include_vars:
        file: extension-preferences_stub.json
        name: firefox_extension_prefs_stub

    - name: stat extension-preferences.json
      stat:
        path: /home/keith/.mozilla/firefox/ansible/extension-preferences.json
      register: extension_preferences_json_stat

#if extension-preferences.json exists
    - name: append to json
      when: extension_preferences_json_stat.stat.exists
      block:
        - name: load json
          slurp: 
            src: /home/keith/.mozilla/firefox/ansible/extension-preferences.json 
          register: firefox_extension_prefs
        - name: combine jsons
          set_fact:
            firefox_extension_prefs_combined: "{{ firefox_extension_prefs.content|b64decode|from_json | default([]) | combine(firefox_extension_prefs_stub) }}"

# if extension-preferences.json does not exist
    - name: create new json
      when: not extension_preferences_json_stat.stat.exists
      block:
         - name: rename json var
           set_fact:
             firefox_extension_prefs_combined: "{{ firefox_extension_prefs_stub }}"

#common
    - name: write var to file
      copy:
        content: "{{ firefox_extension_prefs_combined | to_json }}"
        dest: /home/keith/.mozilla/firefox/ansible/extension-preferences.json

    - name: fix permissions
      file:
        path: /home/keith/.mozilla/firefox/ansible/extension-preferences.json
        mode: 0644
        owner: keith
        group: keith
