---

- name: output thing
  hosts: all
  tasks:
    - name: output thing
      debug:
        msg: "{{ item[1] }} {{ item[0]['value']['size'] }} {{ item[0]['value']['path'] }}"
      loop: "{{ tmpfs_user_block|dict2items| product(gui_users)|list }}"
