
### gnome3 settings ###
- name: configure dconf keys
  tags: gnome3
  block:
    - name: make user-db line in dconf profile
      lineinfile:
        path: /etc/dconf/profile/user
        regexp: '^user-db:.*'
        line: |
          user-db:user
        create: true
    - name: make system-db line in dconf profile
      lineinfile:
        path: /etc/dconf/profile/user
        regexp: '^system-db:.*'
        line: |
          system-db:local
        create: true
- name: make folder for system keyfile for dconf
  tags: gnome3
  file:
    path: /etc/dconf/db/local.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template system keyfile for dconf
  tags: gnome3
  template:
    src: local.j2
    dest: /etc/dconf/db/local.d/00-ansible
    owner: root
    group: root
    mode: 0644
  notify: dconf_update

- name: lock customized keys for dconf
  tags: gnome3
  block:
    - name: make locks folder for dconf
      file:
        path: /etc/dconf/db/local.d/locks
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: move locks template for dconf
      template:
        src: locked.j2
        dest: /etc/dconf/db/local.d/locks/00-ansible
        owner: root
        group: root
        mode: 0644
      notify: dconf_update 


### apt and packages ###
- name: remove unwanted gnome apt packages
  tags: gnome3,apt
  apt:
    name: "{{ gnome3_packages_unwanted }}"
    state: absent
    autoclean: true
    autoremove: true
    purge: true
- name: install gnome3 common packages
  tags: gnome3,apt
  apt:
    name: "{{ gnome3_packages_common }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: unattended-upgrades on shutdown
  tags: gnome3,apt
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: |
      '^Unattended-Upgrade.*InstallOnShutdown.*'
    line: "Unattended-Upgrade::InstallOnShutdown \"true\";"
   #may want to increase logind's InhibitDelayMaxSec to a few minutes to accomodate this

### locales ###
- name: localepurge
  tags: gnome3,locale
  block:
  - name: install localepurge config file
    template:
      src: locale.nopurge.j2
      dest: /etc/locale.nopurge
      owner: root
      group: root
      mode: 0644
    register: locale_nopurge_config_changed  
  - name: run localepurge
    shell:
      cmd: /usr/sbin/localepurge
    when: locale_nopurge_config_changed.changed
    notify: locale_gen
