### tmpfs ###
- name: configure tmpfs for each user
  tags: gnome3
  include_tasks: setup_user_tmpfs.yml
  loop: "{{ gnome3_tmpfs_user_block | dict2items | product(gui_users) | list }}"

### gnome3 settings ###
- name: configure dconf keys
  tags: gnome3
  block:
    - name: make user-db line in dconf profile
      lineinfile:
        path: /etc/dconf/profile/user
        regexp: '^user-db:.*'
        line: |
          user-db:user
        create: true
    - name: make system-db line in dconf profile
      lineinfile:
        path: /etc/dconf/profile/user
        regexp: '^system-db:.*'
        line: |
          system-db:local
        create: true
- name: make folder for system keyfile for dconf
  tags: gnome3
  file:
    path: /etc/dconf/db/local.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: template system keyfile for dconf
  tags: gnome3
  template:
    src: dconf_user_local.j2
    dest: /etc/dconf/db/local.d/00-ansible
    owner: root
    group: root
    mode: 0644
  notify: dconf_update

- name: lock customized keys for dconf
  tags: gnome3
  block:
    - name: make locks folder for dconf
      file:
        path: /etc/dconf/db/local.d/locks
        state: directory
        owner: root
        group: root
        mode: 0755
    - name: move locks template for dconf
      template:
        src: dconf_user_locked.j2
        dest: /etc/dconf/db/local.d/locks/00-ansible
        owner: root
        group: root
        mode: 0644
      notify: dconf_update 

- name: configure gdm3-greeter
  tags: gnome3
  block:
    - template:
        src: dconf_user_local.j2
        dest: /etc/gdm3/greeter.dconf-defaults
        owner: root
        group: root
        mode: 0644
      register: gdm3_greeter_changed
    - shell:
        cmd: dpkg-reconfigure gdm3
      when: gdm3_greeter_changed.changed
  #dconf_update may not apply these, dpkg-reconfigure gdm3 may be needed


### apt and packages ###
- name: remove unwanted gnome apt packages
  tags: gnome3,apt
  apt:
    name: "{{ gnome3_packages_unwanted }}"
    state: absent
    autoclean: true
    autoremove: true
    purge: true
- name: install gnome3 common packages
  tags: gnome3,apt
  apt:
    name: "{{ gnome3_packages_common }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
- name: unattended-upgrades on shutdown
  tags: gnome3,apt
  lineinfile:
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    regexp: |
      '^Unattended-Upgrade.*InstallOnShutdown.*'
    line: "Unattended-Upgrade::InstallOnShutdown \"true\";"
   #may want to increase logind's InhibitDelayMaxSec to a few minutes to accomodate this

### libreoffice ###
- name: configure libreoffice for {{ item }}
  tags: gnome3,libreoffice
  block:
    - name: disable picklist for {{ item }}
      lineinfile:
        path: /home/{{ item }}/.config/libreoffice/4/user/registrymodifications.xcu
        regexp: '<item oor:path="/org.openoffice.Office.Common/History"><prop oor:name="PickListSize" oor:op="fuse"><value>.*</value></prop></item>'
        line: |
          <item oor:path="/org.openoffice.Office.Common/History"><prop oor:name="PickListSize" oor:op="fuse"><value>0</value></prop></item>
      loop: "{{ gui_users }}"
