
### Power Management ###
- name: Check automatic suspend on AC timeout action
  tags: power
  shell:
    cmd: | 
      dbus-launch --exit-with-session gsettings get org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type
  register: sleep_inactive_ac_type
  changed_when: false

- name: Set automatic suspend on AC timeout value
  tags: power
  shell:
    cmd: |
      dbus-launch --exit-with-session gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
  when: sleep_inactive_ac_type.stdout != "'nothing'"

